require("config.options")
require("config.keybinds")
require("config.autocmds")
require("config.lazy")
-- require("custom.colors.customlight").setup()
-- require("custom.colors.customdark").setup()
vim.cmd([[colorscheme monokai-pro]])
