return {
	-- {
	-- 	"kevinhwang91/nvim-ufo",
	-- 	event = "BufEnter",
	-- 	dependencies = {
	-- 		"kevinhwang91/promise-async",
	-- 		"neovim/nvim-lspconfig",
	-- 		"luukvbaal/statuscol.nvim",
	-- 	},
	-- 	config = function()
	-- 		vim.o.foldcolumn = "1"
	-- 		vim.o.foldlevel = 99
	-- 		vim.o.foldlevelstart = 99
	-- 		vim.o.foldenable = true
	--
	-- 		require("ufo").setup({
	-- 			provider_selector = function()
	-- 				return { "treesitter", "indent" }
	-- 			end,
	-- 		})
	-- 	end,
	-- },
}
